name             'magento'
maintainer       'Ivan Chepurnyi'
maintainer_email 'ivan.chepurnyi@ecomdev.org'
license          'GPLv3'
description      'Installs/Configures PHP-FPM pools'
long_description 'Installs/Configures PHP-FPM pools'
version          '0.1.3'

depends 'vhost'
depends 'php_fpm'
depends 'mysql'
depends 'database'
depends 'logrotate'
depends 'ecomdev_common'
depends 'redisio'
depends 'chef-varnish'
